### ISSUE TITLE
[P] Requires win32gui module, which may not be present by default

### ISSUE THREAD

**Issue by brfealy** [rstudio/spark-install#15]
Using vanilla win 10 VM, python.org 3.5.3, and java jdk 1.8.

Attempting install with no versions specified (thus gets latest) gives an error "No module named 'win32gui'
Workaround is to pip install pywin32

Need to either pull this module in if required or find another way to send broadcast message for the environment variable change.

**Comment by drdarshan** [comment]
As of #23, you just get a warning but the install succeeds. It is a bit inconvenient but always doing ``import spark_install; spark_install.spark_install()`` before running ``import pyspark``  doesn't seem that bad.
